on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Compute module size tree and report
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-dev-dependencies: true
